# Generated by Django 4.2 on 2023-07-12 16:42

import QandA.helpers.modelhelpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geografia', '0002_alter_comarca_options_alter_municipi_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipusEspai',
            fields=[
                ('codi', models.CharField(default=QandA.helpers.modelhelpers.calculacodi, editable=False, help_text='Codi intern', max_length=5, primary_key=True, serialize=False, verbose_name='codi')),
                ('text_ca', models.CharField(help_text='Tipus espai en català', max_length=250, verbose_name='Tipus espai (cat)')),
                ('text_es', models.CharField(blank=True, help_text='Tipus espai en castellà', max_length=250, verbose_name='Tipus espai (es)')),
                ('text_en', models.CharField(blank=True, help_text='Tipus espai amb anglès', max_length=250, verbose_name='Tipus espai (en)')),
            ],
            options={
                'verbose_name': "tipus d'espai",
                'verbose_name_plural': "tipus d'espais",
                'ordering': ['text_ca'],
            },
        ),
        migrations.CreateModel(
            name='Espai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text="Nom d'aquest espai", max_length=250, verbose_name='Nom')),
                ('adreca', models.CharField(help_text='Adreça on es troba aquest espai', max_length=250, verbose_name='Adreça')),
                ('municipi', models.ForeignKey(help_text='Municipi on es troba aquest espai', on_delete=django.db.models.deletion.RESTRICT, to='geografia.municipi', verbose_name='Municipi')),
                ('tipus', models.ForeignKey(help_text="Tipus d'espai", on_delete=django.db.models.deletion.RESTRICT, to='espais.tipusespai', verbose_name='Tipus')),
            ],
        ),
    ]
