# Generated by Django 4.2 on 2023-05-26 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comarca',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='municipi',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['nom']},
        ),
    ]
