# Generated by Django 4.2 on 2023-05-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RespostaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='formularis.pregunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='formularis.resposta')),
            ],
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respostes',
            field=models.ManyToManyField(through='formularis.RespostaPregunta', to='formularis.resposta'),
        ),
    ]
