# Generated by Django 4.2 on 2023-06-04 13:35

import QandA.helpers.modelhelpers
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espais', '0001_initial'),
        ('accessibilitats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgrupacioPreguntes',
            fields=[
                ('codi', models.CharField(default=QandA.helpers.modelhelpers.calculacodi, editable=False, help_text='Codi intern', max_length=5, primary_key=True, serialize=False, verbose_name='codi')),
                ('order', models.IntegerField(help_text='Utilitza aquest número per ordenar les agrupacions', verbose_name='Codi ordenació')),
                ('text_ca', models.CharField(help_text='Pregunta en català', max_length=250, verbose_name='Pregunta (cat)')),
                ('text_es', models.CharField(blank=True, help_text='Pregunta en castellà', max_length=250, verbose_name='Pregunta (es)')),
                ('text_en', models.CharField(blank=True, help_text='Pregunta amb anglès', max_length=250, verbose_name='Pregunta (en)')),
                ('tipusespai', models.ForeignKey(editable=False, help_text='A quin tipus espai pertany', on_delete=django.db.models.deletion.RESTRICT, to='espais.tipusespai', verbose_name='Tipus espai')),
            ],
            options={
                'verbose_name': 'agrupació de preguntes',
                'verbose_name_plural': 'agrupacions de preguntes',
                'order_with_respect_to': 'tipusespai',
                'unique_together': {('tipusespai', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('codi', models.CharField(default=QandA.helpers.modelhelpers.calculacodi, editable=False, help_text='Codi intern', max_length=5, primary_key=True, serialize=False, verbose_name='codi')),
                ('text_ca', models.CharField(help_text='Pregunta en català', max_length=250, verbose_name='Pregunta (cat)')),
                ('text_es', models.CharField(blank=True, help_text='Pregunta en castellà', max_length=250, verbose_name='Pregunta (es)')),
                ('text_en', models.CharField(blank=True, help_text='Pregunta amb anglès', max_length=250, verbose_name='Pregunta (en)')),
                ('help_text_ca', models.CharField(help_text='Text ajuda en català', max_length=250, verbose_name='Text ajuda (cat)')),
                ('help_text_es', models.CharField(blank=True, help_text='Text ajuda en castellà', max_length=250, verbose_name='Text ajuda (es)')),
                ('help_text_en', models.CharField(blank=True, help_text='Text ajuda amb anglès', max_length=250, verbose_name='Text ajuda (en)')),
                ('imatge', models.ImageField(blank=True, help_text="\n            Atenció! Aquesta aplicació és inclusiva, la imatge no té\n            text alternatiu i, per tant, ha de ser una ajuda opcional\n            a l'hora de plantejar la pregunta", null=True, upload_to='QandA', verbose_name='Il·lustració de la pregunta')),
            ],
            options={
                'verbose_name': 'preguntes',
                'verbose_name_plural': 'preguntes',
                'ordering': ['text_ca'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaDinsTipusEspai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='Utilitza aquest número per ordenar les respostes', verbose_name='Codi ordenació')),
                ('importancia', models.IntegerField(choices=[(3, 'Alta'), (2, 'Mitja'), (1, 'Baixa')], help_text="Rellevància de la pregunta en aquest tipus d'espai", verbose_name='Importància')),
                ('agrupaciopreguntes', models.ForeignKey(help_text="Dins un tipus d'espai les preguntes s'agrupen en seccions", on_delete=django.db.models.deletion.RESTRICT, to='QandA.agrupaciopreguntes', verbose_name='Secció')),
                ('pregunta', models.ForeignKey(help_text='Pregunta', on_delete=django.db.models.deletion.RESTRICT, to='QandA.pregunta', verbose_name='Pregunta')),
                ('tipusespai_cache', models.ForeignKey(editable=False, help_text='A quin tipus espai pertany', on_delete=django.db.models.deletion.RESTRICT, to='espais.tipusespai', verbose_name='Tipus espai')),
            ],
            options={
                'order_with_respect_to': 'agrupaciopreguntes',
                'unique_together': {('agrupaciopreguntes', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('codi', models.CharField(default=QandA.helpers.modelhelpers.calculacodi, editable=False, help_text='Codi intern', max_length=30, primary_key=True, serialize=False, verbose_name='codi')),
                ('order', models.IntegerField(help_text='Utilitza aquest número per ordenar les respostes', verbose_name='Codi ordenació')),
                ('text_ca', models.CharField(help_text='Resposta en català', max_length=250, verbose_name='Resposta (cat)')),
                ('text_es', models.CharField(blank=True, help_text='Resposta en castellà', max_length=250, verbose_name='Resposta (es)')),
                ('text_en', models.CharField(blank=True, help_text='Resposta amb anglès', max_length=250, verbose_name='Resposta (en)')),
                ('imatge', models.ImageField(blank=True, help_text="\n            Atenció! Aquesta aplicació és inclusiva, la imatge no té\n            text alternatiu i, per tant, ha de ser una ajuda opcional\n            a l'hora de plantejar la resposta", null=True, upload_to='QandA', verbose_name='Il·lustració de la resposta')),
                ('pregunta', models.ForeignKey(editable=False, help_text='Pregunta', on_delete=django.db.models.deletion.RESTRICT, to='QandA.pregunta', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'resposta',
                'verbose_name_plural': 'respostes',
                'order_with_respect_to': 'pregunta',
                'unique_together': {('pregunta', 'order')},
            },
        ),
        migrations.CreateModel(
            name='PuntuacioMaxima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afectacio', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text="Percentatge d'afectació d'aquesta pregunta a una discapacitat. Sol ser 0, 0.25, 0.50 o 1.00", max_digits=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name="Percentatge d'afectació")),
                ('afectacio_x_importancia', models.FloatField(editable=False, help_text="Resultat de multiplicar l'afectació per la seva importància.", verbose_name='Afectacio x importancia')),
                ('punts_sense_arrodonir', models.FloatField(editable=False, help_text='Puntuació ponderada sobre 100 amb decimals.', verbose_name='Puntuació de la resposta (s/100)')),
                ('punts', models.IntegerField(help_text="Puntuació final d'una resposta per a una discapacitat. La suma de totes les puntuacions per un tipus d'espai i discapacitat ha de ser 100.", validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Puntuació de la resposta')),
                ('discapacitat', models.ForeignKey(help_text='Aplicat a certa discapacitat', on_delete=django.db.models.deletion.CASCADE, to='accessibilitats.discapacitat', verbose_name='Discapacitat')),
                ('preguntadinstipusespai', models.ForeignKey(help_text='Pregunta dins una agrupació de preguntes', on_delete=django.db.models.deletion.CASCADE, to='QandA.preguntadinstipusespai', verbose_name='Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='AportacioResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentatge_aportacio', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Valor del 0.1 al 1.00 quen ens indica quin percentatge de la puntuació aporta aquesta resposta al resultat final(normalment 1.0 ó 0.5)', max_digits=2, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)], verbose_name="Percentatge d'aportació al resultat final")),
                ('preguntadinstipusespai', models.ForeignKey(help_text='Pregunta associada una agrupació de preguntes', on_delete=django.db.models.deletion.CASCADE, to='QandA.preguntadinstipusespai', verbose_name='Pregunta')),
                ('resposta', models.ForeignKey(help_text='Aplicat a certa resposta', on_delete=django.db.models.deletion.CASCADE, to='QandA.resposta', verbose_name='Resposta')),
            ],
        ),
    ]
