# Generated by Django 4.2 on 2023-07-11 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('espais', '0001_initial'),
        ('accessibilitats', '0001_initial'),
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exclusio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discapacitat', models.ForeignKey(help_text='Aplicat a certa discapacitat', on_delete=django.db.models.deletion.CASCADE, to='accessibilitats.discapacitat', verbose_name='Discapacitat')),
                ('preguntadinstipusespai', models.ForeignKey(help_text='Pregunta dins una agrupació de preguntes', on_delete=django.db.models.deletion.CASCADE, to='QandA.preguntadinstipusespai', verbose_name='Pregunta')),
                ('resposta', models.ForeignKey(help_text='Aplicat a certa discapacitat', on_delete=django.db.models.deletion.CASCADE, to='QandA.resposta', verbose_name='Discapacitat')),
                ('tipusespai_cache', models.ForeignKey(editable=False, help_text='A quin tipus espai pertany', on_delete=django.db.models.deletion.RESTRICT, to='espais.tipusespai', verbose_name='Tipus espai')),
            ],
        ),
    ]
