# Generated by Django 4.2 on 2023-06-04 13:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('espais', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_TipusEspai_AgrupacionsP',
            fields=[
            ],
            options={
                'verbose_name': 'Tipus espai i seccions',
                'verbose_name_plural': 'Tipus espai i seccions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('espais.tipusespai',),
        ),
        migrations.CreateModel(
            name='P_TipusEspai_Preguntes',
            fields=[
            ],
            options={
                'verbose_name': 'Tipus espai i preguntes',
                'verbose_name_plural': 'Tipus espai i preguntes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('espais.tipusespai',),
        ),
    ]
