# Generated by Django 4.2 on 2023-07-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QandA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Pregunta_i_Respostes',
            fields=[
            ],
            options={
                'verbose_name': 'Pregunta i respostes',
                'verbose_name_plural': 'Preguntes i respostes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QandA.pregunta',),
        ),
        migrations.CreateModel(
            name='P_PreguntaDinsTipusEspai_Exclusions',
            fields=[
            ],
            options={
                'verbose_name': 'Exclusions',
                'verbose_name_plural': 'Exclusions',
                'ordering': ['tipusespai_cache', 'order'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('QandA.preguntadinstipusespai',),
        ),
    ]
